name: Java CI

on: [push]

jobs:
  build:

    runs-on: ubuntu-latest

    steps:
    - uses: actions/checkout@v1
    - name: Set up JDK 1.8
      uses: actions/setup-java@v1
      with:
        java-version: 1.8
        java-package: jdk+fx
    - name: Build with Maven
      run: mvn -B package --file pom.xml

  build2:

    runs-on: ubuntu-latest

    steps:
    - uses: actions/checkout@v1
    - name: Set up JDK 13
      uses: actions/setup-java@v1
      with:
        java-version: 13
        java-package: jdk+fx
    - name: Build with Maven
      run: mvn -B package --file pom.xml

  build14:
    
    runs-on: ubuntu-latest

    steps:
    - uses: actions/checkout@v1
    - run: curl -O "https://download.bell-sw.com/java/14.0.2+13/bellsoft-jdk14.0.2+13-linux-amd64-full.tar.gz"
    - name: Set up JDK 14
      uses: actions/setup-java@v1
      with:
        java-version: 14
        jdkFile: ./bellsoft-jdk14.0.2+13-linux-amd64-full.tar.gz
    - name: Build with Maven
      run: mvn -B package --file pom.xml
